version: "3.8"
services:
    portal:
        restart: on-failure
        build:
            context: ./home-portal
            dockerfile: ./Dockerfile
        volumes:
            - ./home-portal:/portal
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
        ports:
            - 3000:3000
    sim:
        restart: on-failure
        build:
            context: ./home-sim
            dockerfile: ./Dockerfile
        volumes:
            - ./home-sim:/sim
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
        ports:
            - 3001:3001
    server:
        restart: always
        build:
            dockerfile: ./server/Dockerfile
            context: .
        volumes:
            - ./server/server.py:/server/server.py
            - ./server/agents.py:/server/agents.py
            - ./server/modules:/server/modules
            - ./server/run.py:/server/run.py
        environment:
            - WATCHFILES_FORCE_POLLING=true
            - GEMINI_API_KEY=${GEMINI_API_KEY}
            - GEMINI_API_KEY_V2=${GEMINI_API_KEY_V2}
            - GEMINI_API_KEY_V3=${GEMINI_API_KEY_V3}
        ports:
            - 8000:8000
            - 8001:8001
        depends_on:
            - portal